/**
 * 7개 세션의 answer_key_structure 와 grading_strictness 캐시.
 * MCP 로 DB에서 미리 받아 박제한 데이터 — 스크립트가 anon RLS 없이 동작하도록.
 *
 * 갱신 필요 시 (예: 새 세션 추가):
 *   SELECT id, grading_strictness, answer_key_structure FROM exam_sessions WHERE id IN (...)
 * 을 supabase MCP 로 실행해 결과를 여기에 갱신.
 */

import type { AnswerKeyStructure, GradingStrictness } from '../../types/grading';

interface SessionCache {
  strictness: GradingStrictness;
  structure: AnswerKeyStructure;
}

export const ANSWER_KEYS_CACHE: Record<string, SessionCache> = {
  // === ff54uzt: 원당고2 S2-1 시험 ㄷ지 ===
  ff54uzt: {
    strictness: 'lenient',
    structure: {
      title: '원당고2 S2-1 시험 ㄷ지',
      totalQuestions: 50,
      answers: {
        '1': { text: '명상하다', question: 'meditate' },
        '2': { text: '뜨다, 떠다니다; 부유물', question: 'float' },
        '3': { text: '기여하다, 공헌하다, 기부하다', question: 'contribute' },
        '4': { text: '전문 병원, 개인 병원', question: 'clinic' },
        '5': { text: '범위; 정렬시키다', question: 'range' },
        '6': { text: '참을 수 없는', question: 'intolerable' },
        '7': { text: '미신', question: 'superstition' },
        '8': { text: '깃발, 현수막', question: 'banner' },
        '9': { text: '분리하다; 갈라진, 개개의', question: 'separate' },
        '10': { text: '공자의, 유교의', question: 'Confucian' },
        '11': { text: '생기 있게 하다, 고무하다; 살아 있는', question: 'animate' },
        '12': { text: '질식시키다, 숨이 막히다', question: 'choke' },
        '13': { text: '중립의, 공평한', question: 'neutral' },
        '14': { text: '자랑하다, 떠벌리다', question: 'boast' },
        '15': { text: '동시에', question: 'simultaneously' },
        '16': { text: '강제적인, 강박의', question: 'compulsive' },
        '17': { text: '민간 설화, 전설', question: 'folktale' },
        '18': { text: '싸우다, (일과) 씨름하다, 레슬링하다', question: 'wrestle' },
        '19': { text: '본능', question: 'instinct' },
        '20': { text: '초자연적인', question: 'supernatural' },
        '21': { text: '수행하다, 실시하다; 행위, 안내', question: 'conduct' },
        '22': { text: '증진하다, 승진시키다', question: 'promote' },
        '23': { text: '무리, 떼, 군대, 군사', question: 'troop' },
        '24': { text: '괴롭히다', question: 'afflict' },
        '25': { text: '내구성', question: 'durability' },
        '26': { text: '위함, 목적', question: 'sake' },
        '27': { text: '진화하다, 발전하다', question: 'evolve' },
        '28': { text: '대담한, 선이 굵은', question: 'bold' },
        '29': { text: '얕은, 얇은, 피상적인, 천박한', question: 'shallow' },
        '30': { text: '독특한', question: 'peculiar' },
        '31': { text: '고수하다, 충실하다, 집착하다', question: 'adhere' },
        '32': { text: '거대한', question: 'gigantic' },
        '33': { text: '얼룩; 얼룩지게 하다', question: 'stain' },
        '34': { text: '장난, 해악', question: 'mischief' },
        '35': { text: '경험적인, 실증적인', question: 'empirical' },
        '36': { text: '칭찬; 칭찬하다', question: 'compliment' },
        '37': { text: '철수하다, 철회하다, (돈을) 인출하다', question: 'withdraw' },
        '38': { text: '기숙사', question: 'dormitory' },
        '39': { text: '후퇴하다, 물러서다; 퇴각, 후퇴', question: 'retreat' },
        '40': { text: '붙잡다, 이해하다, 파악하다; 꽉 쥐기, 이해', question: 'grasp' },
        '41': { text: '창', question: 'spear' },
        '42': { text: '박수갈채', question: 'applause' },
        '43': { text: '~하는 경향이 있는', question: 'prone' },
        '44': { text: '예시하다, ~의 좋은 예가 되다', question: 'exemplify' },
        '45': { text: '통일성 있는, 조리 있는', question: 'coherent' },
        '46': { text: '직면하다; 얼굴, 표면', question: 'face' },
        '47': { text: '최고의, 훌륭한', question: 'superb' },
        '48': { text: '통지하다, 알리다', question: 'notify' },
        '49': { text: '불합리한, 우스꽝스러운', question: 'absurd' },
        '50': { text: '전반적인, 전체의; 작업복', question: 'overall' },
      },
    },
  },

  // === la29jix: 아라고2 S2 시험 ㄷ지 ===
  la29jix: {
    strictness: 'lenient',
    structure: {
      title: '아라고2 S2 시험 ㄷ지',
      totalQuestions: 50,
      answers: {
        '1': { text: '변화, 이동, 바꾸다, 이동하다', question: 'shift' },
        '2': { text: '그만두다, 중지하다', question: 'cease' },
        '3': { text: '적시다, 젖다, 흡수하다', question: 'soak' },
        '4': { text: '보호하다', question: 'protect' },
        '5': { text: '격렬한, 과감한', question: 'drastic' },
        '6': { text: '턱수염', question: 'beard' },
        '7': { text: '(~할) 운명이다 (to): 운명, 비운, 파멸', question: 'doom' },
        '8': { text: '명령, 지배력: 명령하다, 지휘하다', question: 'command' },
        '9': { text: '귀족의, 고결한', question: 'noble' },
        '10': { text: '원자', question: 'atom' },
        '11': { text: '(가정용) 기구, 장치', question: 'appliance' },
        '12': { text: '고난, 어려움', question: 'hardship' },
        '13': { text: '새롭게 하다, 갱신하다', question: 'renew' },
        '14': { text: '후보자', question: 'candidate' },
        '15': { text: '쌓아 올린 더미, 많은 양: 쌓아 올리다, 축적하다', question: 'pile' },
        '16': { text: '예언하다, 예고하다', question: 'foretell' },
        '17': { text: '작물, 수확', question: 'crop' },
        '18': { text: '지우다, 없애다', question: 'erase' },
        '19': { text: '이상적인: 이상', question: 'ideal' },
        '20': { text: '존재하다, 살아가다', question: 'exist' },
        '21': { text: '뛰어난, 두드러진, 미해결의', question: 'outstanding' },
        '22': { text: '부딪치다: 충돌, 혹', question: 'bump' },
        '23': { text: '(수)공예, 기술, 선박, 비행기', question: 'craft' },
        '24': { text: '배치하다, 처리하다, 경향을 갖게 하다', question: 'dispose' },
        '25': { text: '결과: (결과로) 생기다', question: 'result' },
        '26': { text: '초과, 초과량, 과도함: 초과한, 여분의', question: 'excess' },
        '27': { text: '조절하다, 조정하다', question: 'adjust' },
        '28': { text: '도박하다, 모험하다: 도박, 모험', question: 'gamble' },
        '29': { text: '최상의, 최적의', question: 'optimal' },
        '30': { text: '주요한, 최초(초기)의', question: 'primary' },
        '31': { text: '태양의, 태양열을 이용한', question: 'solar' },
        '32': { text: '왕조, 왕가', question: 'dynasty' },
        '33': { text: '인종의, 민족의', question: 'ethnic' },
        '34': { text: '통합하다, 통일하다', question: 'unify' },
        '35': { text: '뗏목, 고무보트', question: 'raft' },
        '36': { text: '강화, 보강', question: 'reinforcement' },
        '37': { text: '미생물, 세균', question: 'germ' },
        '38': { text: '표류: 표류하다', question: 'drift' },
        '39': { text: '게다가, 더욱이', question: 'furthermore' },
        '40': { text: '처음의, 초기의: 머리글자(이니셜)', question: 'initial' },
        '41': { text: '풍성하게 하다, 부유하게 하다', question: 'enrich' },
        '42': { text: '으깨다, 밀어 넣다', question: 'crush' },
        '43': { text: '천장, 상한선', question: 'ceiling' },
        '44': { text: '관점, 견해, 원근법, 전망', question: 'perspective' },
        '45': { text: '헌납하다, 바치다', question: 'dedicate' },
        '46': { text: '가라앉다', question: 'sink' },
        '47': { text: '궁금해하다, 놀라다: 경탄, 경이', question: 'wonder' },
        '48': { text: '싸우다: 전투', question: 'combat' },
        '49': { text: '널리 퍼진', question: 'widespread' },
        '50': { text: '엄한, 엄격한', question: 'strict' },
      },
    },
  },

  // === nh0h0rg: 원당고1 S2 시험 ㄷ지 ===
  nh0h0rg: {
    strictness: 'lenient',
    structure: {
      title: '원당고1 S2 시험 ㄷ지',
      totalQuestions: 50,
      answers: {
        '1': { text: '우선순위', question: 'priority' },
        '2': { text: '포식자', question: 'predator' },
        '3': { text: '쉽게', question: 'with ease' },
        '4': { text: '조사, 검사', question: 'inspection' },
        '5': { text: '대조적으로', question: 'in contrast' },
        '6': { text: '엄청난', question: 'tremendous' },
        '7': { text: '정복하다', question: 'conquer' },
        '8': { text: '잘못된 믿음', question: 'faulty belief' },
        '9': { text: '극대화하다', question: 'maximize' },
        '10': { text: '추론', question: 'reasoning' },
        '11': { text: '포함하다', question: 'involve' },
        '12': { text: '미묘한', question: 'subtle' },
        '13': { text: '입증하다', question: 'prove' },
        '14': { text: '주장', question: 'argument' },
        '15': { text: '선반', question: 'shelf' },
        '16': { text: '제국', question: 'empire' },
        '17': { text: '~을 낳다', question: 'give birth to' },
        '18': { text: '칭찬하다', question: 'praise' },
        '19': { text: '침입자', question: 'invader' },
        '20': { text: '이론', question: 'theory' },
        '21': { text: '퍼뜨리다', question: 'spread' },
        '22': { text: '대다수', question: 'majority' },
        '23': { text: '한 배에서 난 새끼', question: 'litter' },
        '24': { text: '결국 ~하게 되다', question: 'end up ~ing' },
        '25': { text: '~보다는', question: 'rather than' },
        '26': { text: '채택, 수용', question: 'adoption' },
        '27': { text: '고고학', question: 'archaeology' },
        '28': { text: '~의 경우에는', question: 'in the case of' },
        '29': { text: '무너지다', question: 'fall apart' },
        '30': { text: '대략', question: 'approximately' },
        '31': { text: '실험적으로', question: 'experimentally' },
        '32': { text: '주장하다', question: 'claim' },
        '33': { text: '실험 참가자', question: 'subject' },
        '34': { text: '왜곡하다', question: 'distort' },
        '35': { text: '수많은', question: 'numerous' },
        '36': { text: '허물다', question: 'tear down' },
        '37': { text: '분석', question: 'analysis' },
        '38': { text: '거의 ~하지 않다', question: 'hardly' },
        '39': { text: '찾다, 구하다', question: 'seek' },
        '40': { text: '상상력이 필요한', question: 'imaginative' },
        '41': { text: '동시 발생', question: 'co-occurrence' },
        '42': { text: '판매량', question: 'sales volume' },
        '43': { text: '강조하다', question: 'emphasize' },
        '44': { text: '(경제적으로) 여유가 있다', question: 'afford' },
        '45': { text: '저장하다', question: 'store' },
        '46': { text: '제2차 세계대전 이후의', question: 'post-World War II' },
        '47': { text: '~을 활용하다', question: 'draw upon' },
        '48': { text: '지역, 동네', question: 'neighborhood' },
        '49': { text: '소유 의식', question: 'ownership' },
        '50': { text: '결론', question: 'conclusion' },
      },
    },
  },

  // === 9rz482g: 원당고2 S2-1 시험 답지 ===
  '9rz482g': {
    strictness: 'lenient',
    structure: {
      title: '원당고2 S2-1 시험 답지',
      totalQuestions: 50,
      answers: {
        '1': { text: '갑판', question: 'deck' },
        '2': { text: '읽고 쓸 수 있는', question: 'literate' },
        '3': { text: '뒤; 뒤의, 후방의; 기르다', question: 'rear' },
        '4': { text: '임대; 임대하다', question: 'lease' },
        '5': { text: '설교', question: 'sermon' },
        '6': { text: '육성하다, 촉진하다; 수양의, 위탁의', question: 'foster' },
        '7': { text: '놀라게 하다', question: 'astound' },
        '8': { text: '환호, 갈채; [성원]하다', question: 'cheer' },
        '9': { text: '변수; 변하기 쉬운, 변덕스러운', question: 'variable' },
        '10': { text: '독재자, 구술하는 사람', question: 'dictator' },
        '11': { text: '심리학자', question: 'psychologist' },
        '12': { text: '힘, 영향력; 강요하다', question: 'force' },
        '13': { text: '개혁; 개혁하다', question: 'reform' },
        '14': { text: '통치 기간, 치세; 군림하다', question: 'reign' },
        '15': { text: '평가, 판단', question: 'assessment' },
        '16': { text: '수확하다', question: 'reap' },
        '17': { text: '게시, 게시물', question: 'bulletin' },
        '18': { text: '만(灣)', question: 'bay' },
        '19': { text: '청사진', question: 'blueprint' },
        '20': { text: '둥지, 보금자리; 둥지를 틀다, (둥지에서) 살다', question: 'nest' },
        '21': { text: '치료하다, 해결하다; 치유, 회복', question: 'cure' },
        '22': { text: '괴롭히다, 약 올리다', question: 'tease' },
        '23': { text: '구체적인; 콘크리트', question: 'concrete' },
        '24': { text: '남자의, 남자다운', question: 'masculine' },
        '25': { text: '양철, 주석', question: 'tin' },
        '26': { text: '싹이 트다, 자라나다; 싹', question: 'sprout' },
        '27': { text: '생산(량), 산출(량)', question: 'output' },
        '28': { text: '불평하다, 항의하다', question: 'complain' },
        '29': { text: '황폐시키다', question: 'devastate' },
        '30': { text: '환자; 인내심 있는', question: 'patient' },
        '31': { text: '훔치다, 강탈하다', question: 'rob' },
        '32': { text: '고장, 쇠약', question: 'breakdown' },
        '33': { text: '대리자, 대체물; 대체하다', question: 'substitute' },
        '34': { text: '꿰매다, 바느질하다', question: 'sew' },
        '35': { text: '만족시키다, 충족시키다', question: 'satisfy' },
        '36': { text: '공격적인, 적극적인', question: 'aggressive' },
        '37': { text: '변장하다, 숨기다; 변장, 은폐', question: 'disguise' },
        '38': { text: '낙담시키다, 단념시키다', question: 'discourage' },
        '39': { text: '인내심', question: 'perseverance' },
        '40': { text: '전후 관계, 맥락, 문맥', question: 'context' },
        '41': { text: '조각하다, 새기다', question: 'carve' },
        '42': { text: '다루다, 대처하다(with); 거래', question: 'deal' },
        '43': { text: '중대한, 중요한', question: 'crucial' },
        '44': { text: '싸우다, 주장하다, 경쟁하다', question: 'contend' },
        '45': { text: '적대적인', question: 'hostile' },
        '46': { text: '집회, 총회, 관습', question: 'convention' },
        '47': { text: '영양분을 주다, 기르다', question: 'nourish' },
        '48': { text: '~의 결과로 여기다; 속성', question: 'attribute' },
        '49': { text: '갈라진 틈; 금 가다', question: 'crack' },
        '50': { text: '놀라게 하다, 기절시키다', question: 'stun' },
      },
    },
  },

  // === p344qwb: 원당고2 S2 시험 답지 ===
  p344qwb: {
    strictness: 'lenient',
    structure: {
      title: '원당고2 S2 시험 답지',
      totalQuestions: 50,
      answers: {
        '1': { text: '과잉', question: 'surplus' },
        '2': { text: '수행하다', question: 'carry out' },
        '3': { text: '분석적으로', question: 'analytically' },
        '4': { text: '비자발적인', question: 'involuntary' },
        '5': { text: '~에 영향을 주다', question: 'impact on' },
        '6': { text: '통과하다', question: 'pass through' },
        '7': { text: '선사 시대', question: 'prehistoric times' },
        '8': { text: '간략한 표현', question: 'shorthand' },
        '9': { text: '~에 직면한', question: 'presented with' },
        '10': { text: '경제적 기회', question: 'economic opportunity' },
        '11': { text: '환경적인', question: 'environmental' },
        '12': { text: '전략', question: 'strategy' },
        '13': { text: '부화하다', question: 'hatch' },
        '14': { text: '부서짐, 깨짐', question: 'fracture' },
        '15': { text: '멈추다', question: 'cease' },
        '16': { text: '구술 문화 (말로 전하는 문화)', question: 'oral culture' },
        '17': { text: '과밀하게 만들다', question: 'overcrowd' },
        '18': { text: '출발지', question: 'origin' },
        '19': { text: '외과 의사', question: 'surgeon' },
        '20': { text: '고대 책 형태 (두꺼운 종이를 엮은 것)', question: 'codex' },
        '21': { text: '양생법(養生法)', question: 'regimen' },
        '22': { text: '동물학자', question: 'zoologist' },
        '23': { text: '~에 의해 제공된', question: 'afforded by' },
        '24': { text: '분리하다', question: 'isolate' },
        '25': { text: '스스로', question: "on one's own" },
        '26': { text: '유혹', question: 'temptation' },
        '27': { text: '이주', question: 'migration' },
        '28': { text: '자기 파괴적인', question: 'self-destructive' },
        '29': { text: '쪼개짐', question: 'splitting' },
        '30': { text: '유산', question: 'heritage' },
        '31': { text: '입력, 자극', question: 'input' },
        '32': { text: '조상', question: 'ancestor' },
        '33': { text: '주목할 만한', question: 'remarkable' },
        '34': { text: '전환, 변화', question: 'transition' },
        '35': { text: '해변가', question: 'beachfront' },
        '36': { text: '일관성 없는, 두서없는', question: 'incoherent' },
        '37': { text: '외부 이주', question: 'out-migration' },
        '38': { text: '(대뇌) 변연계(邊緣系)의', question: 'limbic' },
        '39': { text: '반사, 반영', question: 'reflection' },
        '40': { text: '고정된', question: 'static' },
        '41': { text: '감정, 정서', question: 'sentiment' },
        '42': { text: '함의, 암시된 내용', question: 'implication' },
        '43': { text: '환각', question: 'hallucination' },
        '44': { text: '(뇌에) 깊이 박힌, 타고난', question: 'hardwired' },
        '45': { text: '노출시키다', question: 'expose' },
        '46': { text: '오래된', question: 'age-old' },
        '47': { text: '신경과학', question: 'neuroscience' },
        '48': { text: '부피가 큰', question: 'bulky' },
        '49': { text: '감각 차단 탱크', question: 'sensory deprivation tank' },
        '50': { text: '오해의 소지가 있는', question: 'misleading' },
      },
    },
  },

  // === osqg78m: 아라고2 S2 시험 답지 ===
  osqg78m: {
    strictness: 'lenient',
    structure: {
      title: '아라고2 S2 시험 답지',
      totalQuestions: 50,
      answers: {
        '1': { text: '일시적인, 임시의', question: 'temporary' },
        '2': { text: '통근, 통근하다', question: 'commute' },
        '3': { text: '부족, 종족', question: 'tribe' },
        '4': { text: '버리다, 포기하다', question: 'abandon' },
        '5': { text: '거친, 가혹한', question: 'harsh' },
        '6': { text: '심부름, 잡일', question: 'errand' },
        '7': { text: '나타나다', question: 'appear' },
        '8': { text: '대리점', question: 'agency' },
        '9': { text: '짜증 나게 하다, 화나게 하다', question: 'irritate' },
        '10': { text: '탐욕', question: 'greed' },
        '11': { text: '협의회, 회의, 의회', question: 'council' },
        '12': { text: '접다, 포개다; 주름, (동물의) 우리', question: 'fold' },
        '13': { text: '엎지르다, 흘리다; 엎질러짐, 유출', question: 'spill' },
        '14': { text: '의식하고 있는, 의도적인', question: 'conscious' },
        '15': { text: '특성, 특징', question: 'trait' },
        '16': { text: '부과하다, 강요하다', question: 'impose' },
        '17': { text: '북극의', question: 'arctic' },
        '18': { text: '반대의, 불리한; 반대의 것', question: 'contrary' },
        '19': { text: '겸손한, 알맞은', question: 'modest' },
        '20': { text: '복지', question: 'welfare' },
        '21': { text: '감독하다, 관리하다, 통제하다', question: 'supervise' },
        '22': { text: '정복하다, 극복하다', question: 'conquer' },
        '23': { text: '삼키다; 삼킴, 제비', question: 'swallow' },
        '24': { text: '발생하다, 생겨나다', question: 'arise' },
        '25': { text: '전통, 관습', question: 'tradition' },
        '26': { text: '승무원', question: 'crew' },
        '27': { text: '흐릿한, 어두운; (불빛이) 흐려지다', question: 'dim' },
        '28': { text: '고상한, 우아한', question: 'elegant' },
        '29': { text: '양육하다, 교육하다; 양육, 교육', question: 'nurture' },
        '30': { text: '비범한, 놀라운', question: 'extraordinary' },
        '31': { text: '살다, 거주하다', question: 'inhabit' },
        '32': { text: '가상의, 사실상의', question: 'virtual' },
        '33': { text: '영수증', question: 'receipt' },
        '34': { text: '내부의', question: 'inner' },
        '35': { text: '편견, 선입관', question: 'prejudice' },
        '36': { text: '입학하다, 등록하다', question: 'enroll' },
        '37': { text: '보행자; 보행자의', question: 'pedestrian' },
        '38': { text: '공격하다; 공격', question: 'attack' },
        '39': { text: '강벽, 장애물', question: 'barrier' },
        '40': { text: '(눈부시게) 빛나다, 노려보다; 눈부신 빛, 노려봄', question: 'glare' },
        '41': { text: '민감한, 예민한, 세심한', question: 'sensitive' },
        '42': { text: '비극의, 비참한', question: 'tragic' },
        '43': { text: '방해하다, 간섭하다', question: 'interfere' },
        '44': { text: '진술, 성명서', question: 'statement' },
        '45': { text: '영양', question: 'nutrition' },
        '46': { text: '연설하다; 연설, 인사말', question: 'address' },
        '47': { text: '확실하게 하다, 보증하다', question: 'ensure' },
        '48': { text: '제거하다, 배제하다', question: 'eliminate' },
        '49': { text: '토론; 토론하다', question: 'debate' },
        '50': { text: '묽은; 희석시키다', question: 'dilute' },
      },
    },
  },

  // === 8qwac6p: 원당고3 T 단어 재시험 (혼합 영↔한) ===
  '8qwac6p': {
    strictness: 'lenient',
    structure: {
      title: '원당고3 T 단어 재시험',
      totalQuestions: 50,
      answers: {
        '1': { text: '공기 저항', question: 'air drag' },
        '2': { text: '경관, 지형', question: 'landscape' },
        '3': { text: '총알', question: 'bullet' },
        '4': { text: '인상', question: 'impression' },
        '5': { text: '굶주리다', question: 'starve' },
        '6': { text: '쿼터백(미식축구의 중간 위치에서 뛰면서 공격을 지휘하는 선수)', question: 'quarterback' },
        '7': { text: '가상의', question: 'virtual' },
        '8': { text: '펄프 공장', question: 'pulp mill' },
        '9': { text: '관점', question: 'perspective' },
        '10': { text: '바꾸다, 수정하다', question: 'modify' },
        '11': { text: '번식', question: 'breeding' },
        '12': { text: '중단하다', question: 'halt' },
        '13': { text: '상대적인', question: 'relative' },
        '14': { text: '운동, 움직임', question: 'motion' },
        '15': { text: '비밀 보호', question: 'confidentiality' },
        '16': { text: '미국 프로 미식축구 연맹', question: 'NFL' },
        '17': { text: '상대적인', question: 'relative' },
        '18': { text: '영구적으로', question: 'permanently' },
        '19': { text: '강력한', question: 'potent' },
        '20': { text: '만족스럽지 못한', question: 'unsatisfactory' },
        '21': { text: '지배적인', question: 'dominant' },
        '22': { text: '포함하다', question: 'capture' },
        '23': { text: '농촌의, 시골의', question: 'rural' },
        '24': { text: '장벽', question: 'barrier' },
        '25': { text: '친밀한', question: 'intimate' },
        '26': { text: 'seed', question: '씨앗' },
        '27': { text: 'rot', question: '썩히다' },
        '28': { text: 'contain', question: '포함하다' },
        '29': { text: 'connectivity', question: '연결성' },
        '30': { text: 'locate', question: '표시하다, 찾아내다' },
        '31': { text: 'custom', question: '관행, 관습' },
        '32': { text: 'deep-freeze', question: '급속 냉동의, 매우 차가운' },
        '33': { text: 'interception', question: '가로채기' },
        '34': { text: 'homely', question: '흔한' },
        '35': { text: 'emission', question: '배출' },
        '36': { text: 'decomposition', question: '분해' },
        '37': { text: 'disastrous', question: '재앙인' },
        '38': { text: 'extreme', question: '극단적인' },
        '39': { text: 'substantially', question: '크게, 상당히' },
        '40': { text: 'catalog', question: '분류하다' },
        '41': { text: 'stretch', question: '뻗다' },
        '42': { text: 'wander', question: '돌아다니다, 배회하다' },
        '43': { text: 'anthropology', question: '인류학' },
        '44': { text: 'explicit', question: '명시적인' },
        '45': { text: 'devise', question: '고안하다' },
        '46': { text: 'account for', question: '~을 설명하다' },
        '47': { text: 'heritage site', question: '유적지' },
        '48': { text: 'informant', question: '정보 제공자' },
        '49': { text: 'unjustified', question: '정당하지 않은' },
        '50': { text: 'confine', question: '국한시키다' },
      },
    },
  },
};
